fix: Replace headers.pop() with del for MutableHeaders compatibility Fixed AttributeError in SecurityHeadersMiddleware where response.headers.pop() was used, but MutableHeaders doesn't have a pop() method.
Changed from:
  response.headers.pop('Server', None)

To:
  try:
      del response.headers['Server']
  except KeyError:
      pass

This is the correct way to remove headers from Starlette's MutableHeaders object.

Resolves: AttributeError: 'MutableHeaders' object has no attribute 'pop'